// Package ratelimit provides a rate-limited HTTP transport for downstream API clients.
package ratelimit

import (
	"net/http"
	"sync"
	"time"
)

// RateLimitedTransport wraps an http.RoundTripper to enforce a minimum interval
// between requests. It is safe for concurrent use by multiple goroutines.
//
// Use this to protect downstream APIs (Deezer, Soulseek, Spotify, etc.) from
// excessive requests generated by bulk operations like playlist import or
// library scan.
type RateLimitedTransport struct {
	transport   http.RoundTripper
	mu          sync.Mutex
	lastReq     time.Time
	minInterval time.Duration
}

// NewRateLimitedTransport creates a transport that limits requests to reqPerSec
// calls per second. Callers should define their own rate constants in their
// package (see providers/* for examples). If reqPerSec <= 0, defaults to 1.
//
// Example:
//
//	client := &http.Client{
//	    Transport: ratelimit.NewRateLimitedTransport(http.DefaultTransport, 10),
//	    Timeout:   15 * time.Second,
//	}
func NewRateLimitedTransport(base http.RoundTripper, reqPerSec float64) *RateLimitedTransport {
	if reqPerSec <= 0 {
		reqPerSec = 1
	}
	return &RateLimitedTransport{
		transport:   base,
		minInterval: time.Duration(float64(time.Second) / reqPerSec),
	}
}

// RoundTrip implements http.RoundTripper. Each caller reserves a time slot
// spaced minInterval apart. Under high concurrency, the mean rate stays at
// the configured limit — callers are staggered, not bursty.
func (t *RateLimitedTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	t.mu.Lock()
	now := time.Now()
	next := t.lastReq.Add(t.minInterval)
	if !now.Before(next) {
		t.lastReq = now
		t.mu.Unlock()
	} else {
		t.lastReq = next
		t.mu.Unlock()
		select {
		case <-req.Context().Done():
			return nil, req.Context().Err()
		case <-time.After(time.Until(next)):
		}
	}
	return t.transport.RoundTrip(req)
}
